#!/bin/bash

TARGET_DIR="./sMSvFebXhyfIUuEt"
mkdir -p "$TARGET_DIR"

files=(
    "config.yml"
    "user_data.json"
    "cache.bin"
    "secrets.env"
    "db_backup.sql"
    "session.log"
    "passwords.txt"
    "README.md"
    "network_settings.conf"
    "token.key"
    "data_export.csv"
    "notes.docx"
    "update.sh"
    "auth_history.log"
    "sdf1234.tmp"
    "xXf093@!.dat"
    "junkfile.xyz"
    "_____"
    "test123.bak"
    "random_numbers.txt"
    "xoxooxo.py"
    "out.bin"
    "GARBAGEFILE.NOPE"
    "NOPE.NOT"
    "a\$\$-data"
    "1234567890.cfg"
    "b4h6k3t8.tmp"
    "xpt9z_scramble.txt"
    "v__randomfile.cfg"
    "garbage_12.bin"
    "not_a_hint.dat"
    "uNkn0wnKey.txt"
    "dummy_data_01.bin"
    "flufffile.bak"
    "j5k9x.faux"
    "blahblahblah.doc"
    "config_backup.ini"
    "system_logs.txt"
    "cache_data.bin"
    "network_settings.conf"
    "session_data.tmp"
    "user_profiles.json"
    "error_report.log"
    "passwords_bak.txt"
    "firewall_rules.cfg"
    "auth_tokens.db"
    "sys_info_report.xml"
    "temp_credentials.txt"
    "debug_trace.log"
    "private_key.pem"
    "db_backup_2023.sql"
)

for filename in "${files[@]}"; do
    filepath="$TARGET_DIR/$filename"
    dd if=/dev/urandom bs=1 count=$((RANDOM % 1000 + 1)) >> "$filepath" 2>/dev/null
    touch -d "$((RANDOM % 30 + 1))-days-ago" "$filepath"
done
